config/routes.rb
Rails.application.routes.draw do
  resources :readers
  resources :categories do
    get :report, on: :collection
  end
  resources :books
  resources :readers_books

  devise_for :admins
  root to: 'books#index'
end

app/models/readers_book.rb
class ReadersBook < ApplicationRecord
  belongs_to :book
  belongs_to :reader
end

app/controllers/readers_books_controller.rb
class ReadersBooksController < ApplicationController
  before_action :set_readers_book, only: [:show, :edit, :update, :destroy]

  def index
    @readers_books = ReadersBook.all
  end

  def show
  end

  def new
    @readers_book = ReadersBook.new
  end

  def edit
  end

  def create
    @readers_book = ReadersBook.new(readers_book_params)

    respond_to do |format|
      if @readers_book.save
        format.html { redirect_to @readers_book }
        format.json { render :show, status: :created, location: @readers_book }
      else
        format.html { render :new }
        format.json { render json: @readers_book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @readers_book.update(readers_book_params)
        format.html { redirect_to @readers_book }
        format.json { render :show, status: :ok, location: @readers_book }
      else
        format.html { render :edit }
        format.json { render json: @readers_book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @readers_book.destroy
    respond_to do |format|
      format.html { redirect_to readers_books_url }
      format.json { head :no_content }
    end
  end

  private
  def set_readers_book
    @readers_book = ReadersBook.find(params[:id])
  end

  def readers_book_params
    params.require(:readers_book).permit(:reader_id, :book_id, :checked_out_at, :due_to_return_at, :returned_at)
  end
end

app/helpers/readers_books_helper.rb
module ReadersBooksHelper
end

app/views/readers_books/_form.html.erb
<%= form_with(model: readers_book, local: true) do |form| %>
  <% if readers_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(readers_book.errors.count, "error") %> prohibited this readers_book from being saved:</h2>

      <ul>
      <% readers_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :book %>
    <%= form.select("book_id", Book.all.collect {|p| [ p.title, p.id ] }, {}, {class:"form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label :reader %>
    <%= form.select("reader_id", Reader.all.collect {|p| [ p.full_name, p.id ] }, {}, {class:"form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label :checked_out_at %>
    <%= form.datetime_select :checked_out_at, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_to_return_at %>
    <%= form.datetime_select :due_to_return_at, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :returned_at %>
    <%= form.datetime_select :returned_at, {:include_blank => true, :default => nil, class: 'form-control'} %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/readers_books/_reader_book.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="record-info">
      <div class="record-info-row">
        <div class="record-title"><%= reader_book.book.title %></div>
      </div>
      <div class="record-info-row">
        <div class="record-subtext">published by <%= reader_book.reader.second_name %></div>
        <div class="record-links">
          <%= link_to book do %>
            <%= fa_icon "eye" %>
          <% end %>
          <%= link_to edit_book_path(book) do %>
            <%= fa_icon "edit" %>
          <% end %>
          <%= link_to book, method: :delete, data: {confirm: 'Are you sure?'} do %>
            <%= fa_icon "trash" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/readers_books/edit.html.erb
<%= render 'form', readers_book: @readers_book %>


<div class="d-flex flex-column">
    <%= link_to 'Show', @readers_book %>
    <%= link_to 'Back', readers_books_path %>
</div>

app/views/readers_books/index.html.erb
<%= link_to 'New Readers Book', new_readers_book_path %>

<table class = 'table'>
  <thead>
    <tr>
      <th>Book</th>
      <th>Reader</th>
      <th>Checked out at</th>
      <th>Due to return at</th>
      <th>Returned at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readers_books.each do |readers_book| %>
      <tr>
        <td><%= link_to readers_book.book.title, readers_book.book %></td>
        <td><%= link_to readers_book.reader.full_name, readers_book.reader %></td>
        <td><%= readers_book.checked_out_at %></td>
        <td><%= readers_book.due_to_return_at %></td>
        <td><%= readers_book.returned_at %></td>
        <td><%= link_to readers_book do %>
            <%= fa_icon "eye" %>
          <% end %></td>
        <td><%= link_to edit_readers_book_path(readers_book) do %>
            <%= fa_icon "edit" %>        
            <% end %></td>
        <td><%= link_to  readers_book, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= fa_icon "trash" %>        
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers_books/new.html.erb
<%= render 'form', readers_book: @readers_book %>

<%= link_to 'Back', readers_books_path %>

app/views/readers_books/show.html.erb
<p>
  <strong>Book:</strong>
  <%= render partial: 'books/book', locals: {book: @readers_book.book} %>
</p>

<p>
  <strong>Reader:</strong>
  <%= render partial: 'readers/reader', locals: {reader: @readers_book.reader} %>
</p>

<p>
  <strong>Checked out at:</strong>
  <%= @readers_book.checked_out_at %>
</p>

<p>
  <strong>Due to return at:</strong>
  <%= @readers_book.due_to_return_at %>
</p>

<p>
  <strong>Returned at:</strong>
  <%= @readers_book.returned_at %>
</p>

<div class="d-flex flex-column">
  <%= link_to 'Edit', edit_readers_book_path(@readers_book) %>
  <%= link_to 'Back', readers_books_path %>
</div>