config/routes.rb
Rails.application.routes.draw do
  resources :readers
  resources :categories do
    get :report, on: :collection
  end
  resources :books
  resources :readers_books

  devise_for :admins
  root to: 'books#index'
end

app/models/reader.rb
class Reader < ApplicationRecord
  has_and_belongs_to_many :books

  validates :first_name, :second_name, :patronymic, :home_address, :work_address, :phone, :passport,
            presence: true, length: { minimum: 3, maximum: 50 }

  validates :born_on, presence: true

  def full_name
    "#{second_name} #{first_name} #{patronymic}"
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]
  before_action :save_filters, only: :index

  # GET /readers
  # GET /readers.json
  def index
    @readers = TextFilter.new(Reader.all, filter_params).call
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html {redirect_to @reader, notice: 'Reader was successfully created.'}
        format.json {render :show, status: :created, location: @reader}
      else
        format.html {render :new}
        format.json {render json: @reader.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /readers/1
  # PATCH/PUT /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html {redirect_to @reader, notice: 'Reader was successfully updated.'}
        format.json {render :show, status: :ok, location: @reader}
      else
        format.html {render :edit}
        format.json {render json: @reader.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader.destroy
    respond_to do |format|
      format.html {redirect_to readers_url, notice: 'Reader was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reader
    @reader = Reader.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reader_params
    params.require(:reader).permit(:first_name, :second_name, :patronymic, :born_on, :home_address, :work_address, :phone, :passport)
  end

  def filter_params
    filters = params.permit(filters: %i[first_name second_name patronymic home_address work_address passport])
    filters[:filters]
  end

  def save_filters
    @filters = OpenStruct.new(filter_params)
  end
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/readers/_form.html.erb
<%= form_with(model: reader, local: true) do |form| %>
  <% if reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
      <% reader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :second_name %>
    <%= form.text_field :second_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :patronymic %>
    <%= form.text_field :patronymic, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :born_on %>
    <%= form.date_select :born_on, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :home_address %>
    <%= form.text_area :home_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :work_address %>
    <%= form.text_area :work_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :passport %>
    <%= form.text_field :passport, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/readers/_reader.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="record-info">
      <div class="record-info-row">
        <div class="record-title"><%= "#{reader.second_name} #{reader.first_name}" %></div>
        <div class="record-subtext"><%= reader.patronymic %></div>
      </div>
      <div class="record-info-row">
        <div class="record-subtext"><%= reader.home_address %></div>
        <div class="record-subtext"><%= reader.phone %></div>
        <div class="record-links">
          <%= link_to reader do %>
            <%= fa_icon "eye" %>
          <% end %>
          <%= link_to edit_reader_path(reader) do %>
            <%= fa_icon "edit" %>
          <% end %>
          <%= link_to reader, method: :delete, data: {confirm: 'Are you sure?'} do %>
            <%= fa_icon "trash" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/readers/edit.html.erb
<%= render 'form', reader: @reader %>

<div class="d-flex flex-column">
  <%= link_to 'Show', @reader %>
  <%= link_to 'Back', readers_path %>
</div>

app/views/readers/index.html.erb
<%= link_to 'New Reader', new_reader_path %>

<% filter_fields = [{name: :first_name}, {name: :second_name},
                    {name: :patronymic},{name: :home_address},
                    {name: :work_address}, {name: :passport},
                    {name: :born_on, type: :date}] %>
<div class="d-flex">
  <div class="mr-3 mb-3">
    <%= render partial: 'shared/filters', locals: {fields: filter_fields} %>
  </div>
  <div>
    <% @readers.each do |reader| %>
      <%= render partial: 'reader', locals: {reader: reader} %>
    <% end %>
  </div>
</div>

app/views/readers/new.html.erb
<h1>New Reader</h1>

<%= render 'form', reader: @reader %>

<%= link_to 'Back', readers_path %>

app/views/readers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @reader.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @reader.second_name %>
</p>

<p>
  <strong>Patronymic:</strong>
  <%= @reader.patronymic %>
</p>

<p>
  <strong>Born on:</strong>
  <%= @reader.born_on %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @reader.home_address %>
</p>

<p>
  <strong>Work address:</strong>
  <%= @reader.work_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reader.phone %>
</p>

<p>
  <strong>Passport:</strong>
  <%= @reader.passport %>
</p>

<%= link_to 'Edit', edit_reader_path(@reader) %> |
<%= link_to 'Back', readers_path %>