config/routes.rb
Rails.application.routes.draw do
  resources :readers
  resources :categories do
    get :report, on: :collection
  end
  resources :books
  resources :readers_books

  devise_for :admins
  root to: 'books#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Books</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Library", books_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Books", books_path, class: "nav-item nav-link" %>
      <%= link_to "Categories", categories_path, class: "nav-item nav-link" %>
      <%= link_to "Readers", readers_path, class: "nav-item nav-link" %>
      <%= link_to "Readers-Books", readers_books_path, class: "nav-item nav-link" %>
    </div>
  </div>
  <div class="navbar-nav">
    <% if admin_signed_in? %>
      <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "nav-item nav-link" %>
    <% else %>
      <%= link_to "Sign in", new_admin_session_path, class: "nav-item nav-link" %>
      <%= link_to "Sign up", new_admin_registration_path, class: "nav-item nav-link" %>
    <% end %>

  </div>
</nav>
<% if notice %>
  <p class="alert alert-primary"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="page-content">
  <%= yield %>
</div>
</body>
</html>